[package]
name = "ezcp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
termsize = "0.1"
fs_extra = "1.3"
anyhow = "1.0"