name: Rust

on:
   push:
     branches: [ "main" ]
   pull_request:
     branches: [ "main" ]

env:
   CARGO_TERM_COLOR: always



jobs:
   test_linux:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - run: rustup toolchain install stable --profile minimal
     - name: Rust Cache
       uses: Swatinem/rust-cache@v2.7.3
     - name: Run tests
       run: cargo test --verbose
       
   test_macos:
     
     runs-on: macos-latest
     
     steps:
       - uses: actions/checkout@v3
       - run: rustup toolchain install stable --profile minimal
       - name: Rust Cache
         uses: Swatinem/rust-cache@v2.7.3
       - name: Run tests
         run: cargo test --verbose
       
   test_windows:
     
     runs-on: windows-latest
     
     steps:
      - uses: actions/checkout@v3
      - name: Install MSYS2 with mingw64 toolchain
        uses: msys2/setup-msys2@v2
        with:
          release: false
          update: true
          install: >
            base-devel
            mingw-w64-x86_64-toolchain
          msystem: MINGW64
      - name: Set GCC_PATH
        shell: powershell
        run: echo "GCC_PATH=C:\msys64\mingw64\bin\g++.exe" >> $env:GITHUB_ENV
      - run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.3
      - name: Run tests (MINGW64 shell)
        shell: msys2 {0}
        run: cargo test --verbose
